# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(666, 483)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 651, 341))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelCamLeft = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelCamLeft.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelCamLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCamLeft.setObjectName("labelCamLeft")
        self.horizontalLayout.addWidget(self.labelCamLeft)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.labelCamRight = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelCamRight.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCamRight.setObjectName("labelCamRight")
        self.horizontalLayout.addWidget(self.labelCamRight)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 360, 651, 76))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelSpeed = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSpeed.setObjectName("labelSpeed")
        self.horizontalLayout_2.addWidget(self.labelSpeed)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelGpu = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelGpu.setObjectName("labelGpu")
        self.gridLayout_2.addWidget(self.labelGpu, 1, 0, 1, 1)
        self.labelCpu = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelCpu.setObjectName("labelCpu")
        self.gridLayout_2.addWidget(self.labelCpu, 0, 0, 1, 1)
        self.labelWattNum = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelWattNum.setObjectName("labelWattNum")
        self.gridLayout_2.addWidget(self.labelWattNum, 2, 1, 1, 1)
        self.labelWatt = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelWatt.setObjectName("labelWatt")
        self.gridLayout_2.addWidget(self.labelWatt, 2, 0, 1, 1)
        self.labelGpuNum = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelGpuNum.setObjectName("labelGpuNum")
        self.gridLayout_2.addWidget(self.labelGpuNum, 1, 1, 1, 1)
        self.labelCpuNum = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelCpuNum.setObjectName("labelCpuNum")
        self.gridLayout_2.addWidget(self.labelCpuNum, 0, 1, 1, 1)
        self.checkBoxCamFront = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBoxCamFront.setObjectName("checkBoxCamFront")
        self.gridLayout_2.addWidget(self.checkBoxCamFront, 0, 2, 1, 1)
        self.checkBoxCamLeft = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBoxCamLeft.setObjectName("checkBoxCamLeft")
        self.gridLayout_2.addWidget(self.checkBoxCamLeft, 1, 2, 1, 1)
        self.checkBoxCamRight = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBoxCamRight.setObjectName("checkBoxCamRight")
        self.gridLayout_2.addWidget(self.checkBoxCamRight, 2, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 666, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelCamLeft.setText(_translate("MainWindow", "左畫面"))
        self.labelCamRight.setText(_translate("MainWindow", "右畫面"))
        self.labelSpeed.setText(_translate("MainWindow", "99 Km/H"))
        self.labelGpu.setText(_translate("MainWindow", "GPU(%):"))
        self.labelCpu.setText(_translate("MainWindow", "CPU(%):"))
        self.labelWattNum.setText(_translate("MainWindow", "--"))
        self.labelWatt.setText(_translate("MainWindow", "耗電量(W):"))
        self.labelGpuNum.setText(_translate("MainWindow", "--"))
        self.labelCpuNum.setText(_translate("MainWindow", "--"))
        self.checkBoxCamFront.setText(_translate("MainWindow", "前鏡頭"))
        self.checkBoxCamLeft.setText(_translate("MainWindow", "左鏡頭"))
        self.checkBoxCamRight.setText(_translate("MainWindow", "右鏡頭"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
